### ISSUE TITLE
Removing owned articles

### ISSUE THREAD

**Issue by lusarz** [driggl/linklog#40]
## Overview

User can remove only owned articles

### Todo

- [x] Show trash icon next to the owned articles on the articles list
- [x] Show trash icon on the details page
- [x] Show the confirmation dialog after clicking on the trash icon
- [x] Show the notification when article is removed.

### Resources

- Idea for Vuetify component you could use for notifications: https://vuetifyjs.com/en/components/snackbars/

**Comment by lusarz** [comment]
@swilgosz Do you have any suggestion which notifications library should I use ? I see there is `v-snack` in vuetify available:
https://vuetifyjs.com/en/components/snackbars/

And also a few vue libraries described here:
https://madewithvuejs.com/blog/best-vue-js-notification-components

**Comment by swilgosz** [comment]
Until there is a reason behind it, I would go with a built-in solution.
